# Set site parameters
SITE_NAME = 'jobitos'
SITE_VERSION = '0.1'
# Set person parameters
EMAIL_LENGTH_MAXIMUM = 48
NICKNAME_LENGTH_MINIMUM = 3
NICKNAME_LENGTH_MAXIMUM = 32
USERNAME_LENGTH_MINIMUM = 6
USERNAME_LENGTH_MAXIMUM = 32
PASSWORD_LENGTH_MINIMUM = 6
PASSWORD_LENGTH_AVERAGE = 16
TICKET_LENGTH = 32
TICKET_LIFESPAN_IN_DAYS = 1
REJECTION_LIMIT = 3
MINUTES_OFFSET_DEFAULT = 240
# Set jobito parameters
TITLE_LENGTH_MINIMUM = 32
TITLE_LENGTH_MAXIMUM = 128
DESCRIPTION_LENGTH_MINIMUM = 32
BUDGET_MINIMUM = 10
